repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-json
    -   id: pretty-format-json
    -   id: check-merge-conflict
-   repo: https://github.com/realm/SwiftLint
    rev: 0.52.2
    hooks:
    -   id: swiftlint
        entry: swiftlint --fix --format --progres --config .swiftlint.yml
        stages: [pre-commit]
-   repo: https://github.com/nicklockwood/SwiftFormat/
    rev: 0.51.10
    hooks:
    -   id: swiftformat
        entry: swiftformat --config $DIR/../.swiftformat
        stages: [pre-commit]
