repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/realm/SwiftLint
    rev: 0.52.2
    hooks:
    -   id: swiftlint
        entry: swiftlint --fix --progress --quiet  --config .swiftlint.yml
