name: CI-macOS

on:
  push:
    branches:
      - develop
  pull_request:
    branches: [ develop ]

concurrency:
   group: ci-macos.${{ github.head_ref }}
   cancel-in-progress: true

jobs:
  build:
    name: CI for macOS
    runs-on: macos-13

    # timeout-minutes: 10

    steps:
      - name: Check out project
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: CI for macOS
        run: make ci_macos
