name: CI

on:
  push: 
    branches: 
      - develop

concurrency:
   group: ci.${{ github.head_ref }}
   cancel-in-progress: true

jobs: 
  build:
    name: Build Workspace
    runs-on: macos-latest
    steps:
      - name: Check out project
        uses: actions/checkout@v3

      # Get xcode version from project
      - name: Determine Xcode Version
        id: xcode-version
        shell: bash
        run: |
          echo "::set-output name=version::$(cat .xcode-version)"

      # Make sure we use the correct xcode version
      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ steps.xcode-version.outputs.version }}

      - name: Build Project
        uses: tuist/tuist-action@0.13.0
        with:
          command: 'build'
          arguments: ''
