name: CI

on:
  push: 
    branches: 
      - develop

concurrency:
   group: ci.${{ github.head_ref }}
   cancel-in-progress: true

jobs: 
  build:
    name: Build Workspace
    runs-on: macos-latest
    steps:
      - name: Check out project
        uses: actions/checkout@v3

      - name: Build Project
        uses: tuist/tuist-action@0.13.0
        with:
          command: 'build'
          arguments: ''
