# This workflow will build a Swift project
name: Swift

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: macos-latest
    steps:
    - name: Checkout Project
